baskets/urls.py
from django.urls import path
# baskets_remove
from baskets.views import baskets_add, BasketRemove , baskets_edit

app_name = 'baskets'

urlpatterns = [
    path('baskets_add/<int:id>', baskets_add, name='baskets_add'),
    # path('baskets_remove/<int:id>', baskets_remove, name='baskets_remove'),
    path('baskets_remove/<int:pk>', BasketRemove.as_view(), name='baskets_remove'),
    path('baskets_edit/<int:id>/<int:quantity>/', baskets_edit, name='baskets_edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('ordersapp/', include('ordersapp.urls', namespace='ordersapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [path('^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

app_name = 'ordersapp'

from .views import OrderList, OrderUpdate, OrderDelete, OrderRead, OrderCreate, order_forming_complete, get_product_price

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('read/<int:pk>/', OrderRead.as_view(), name='read'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('forming-complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('product/<int:pk>/price/',get_product_price, name='product_price'),

]

users/urls.py
from django.urls import path

from users.views import login,registration, logout, profile, verify

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('verify/<str:email>/<str:activation_key>', verify, name='verify')
]

baskets/models.py
from django.db import models
from django.utils.functional import cached_property

from users.models import User
from products.models import Product


# class BasketQuerySet(models.QuerySet):
#
#     def delete(self, *args, **kwargs):
#         for item in self:
#             item.product.quantity -= item.quantity
#             item.product.save()
#         super(BasketQuerySet, self).delete(*args, **kwargs)
#

class Basket(models.Model):
    # objects = BasketQuerySet.as_manager()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    created_timestamp = models.DateTimeField(auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'Basket for {self.user.username} | Products {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    @cached_property
    def get_items_cached(self):
        return self.user.basket.select_related()

    def total_quantity(self):
        items = self.get_items_cached
        return sum(item.quantity for item in items)

    def total_price(self):
        items = self.get_items_cached
        return sum(item.sum() for item in items)

    @staticmethod
    def get_item(pk):
        return Basket.objects.get(pk=pk).quantity

    # def delete(self,*args,**kwargs):
    #     self.product.quantity += self.quantity
    #     self.save()
    #     super(Basket, self).delete(*args, **kwargs)
    #
    #
    # def save(self, *args, **kwargs):
    #     super(Basket, self).save(*args, **kwargs)

baskets/views.py
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView

from products.models import Product
from baskets.models import Basket


@login_required
def baskets_add(request, id):
    product = Product.objects.get(id=id)
    baskets = Basket.objects.filter(user=request.user, product=product)
    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        baskets = baskets.first()
        baskets.quantity += 1
        baskets.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



class BasketRemove(DeleteView):
    model = Basket
    success_url = reverse_lazy('users:profile')

@login_required
def baskets_edit(request, id, quantity):
    if request.is_ajax():
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.objects.filter(user=request.user)
        context ={'baskets': baskets}
        result = render_to_string('baskets/baskets.html', context)
        return JsonResponse({'result':result})

baskets/templates/baskets/basket_confirm_delete.html
{% extends 'users/profile.html' %}
{% load static %}

{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="text-center">
        <div class="p-5">
            <div class="category_delete">
                <div class="h3">Уверены, что хотите удалить товар '{{ basket.product.name }}' из корзины?</div>
                <form action="{% url 'baskets:baskets_remove' basket.pk %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Удалить">
                </form>
                <button class="btn btn-success mt-4">
                    <a href="{% url 'users:profile' %}">Отмена</a>
                </button>
            </div>
        </div>
    </div>
{% endblock %}

baskets/templates/baskets/baskets.html
<div class="basket_list">
    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>
        <div class="card mb-3">

            {% for basket in baskets %}
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ basket.id }}" type="number" class="form-control"
                                       value="{{ basket.quantity }}" min="1">
                            </div>
                            <div class="col-lg-4">{{ basket.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:baskets_remove' basket.pk %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            {% endfor %}
        </div>
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ baskets.0.total_price }} руб.</h4>
            </div>
        </div>
        <a href="{% url 'ordersapp:create' %}" type="button"  class="btn btn-success btn-lg float-right">Оформить</a>
    {% else %}
        <h4 class="mt-3 mb-3 text-center">
            Корзина пуста
        </h4>
    {% endif %}
</div>