baskets/urls.py
from django.urls import path
# baskets_remove
from baskets.views import baskets_add, BasketRemove , baskets_edit

app_name = 'baskets'

urlpatterns = [
    path('baskets_add/<int:id>', baskets_add, name='baskets_add'),
    # path('baskets_remove/<int:id>', baskets_remove, name='baskets_remove'),
    path('baskets_remove/<int:pk>', BasketRemove.as_view(), name='baskets_remove'),
    path('baskets_edit/<int:id>/<int:quantity>/', baskets_edit, name='baskets_edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', include('social_django.urls', namespace='social')),
    path('ordersapp/', include('ordersapp.urls', namespace='ordersapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar

    urlpatterns += [path('^__debug__/', include(debug_toolbar.urls))]

ordersapp/urls.py
from django.urls import path

app_name = 'ordersapp'

from .views import OrderList, OrderUpdate, OrderDelete, OrderRead, OrderCreate, order_forming_complete, get_product_price

urlpatterns = [
    path('', OrderList.as_view(), name='list'),
    path('update/<int:pk>/', OrderUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDelete.as_view(), name='delete'),
    path('read/<int:pk>/', OrderRead.as_view(), name='read'),
    path('create/', OrderCreate.as_view(), name='create'),
    path('forming-complete/<int:pk>/', order_forming_complete, name='forming_complete'),
    path('product/<int:pk>/price/',get_product_price, name='product_price'),

]

products/urls.py
from django.urls import path

from django.urls import path
from django.views.decorators.cache import cache_page

from products.views import products, ProductPage

app_name = 'products'

urlpatterns = [
    # path('', products, name='index'),
path('', cache_page(3600)(products), name='index'),
    path('category/<int:id>', products, name='category'),
    path('page/<int:page>', products, name='page'),
    path('product_page/<int:pk>', ProductPage.as_view(), name='product_page')

]

users/urls.py
from django.urls import path

from users.views import login,registration, logout, profile, verify

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    path('verify/<str:email>/<str:activation_key>', verify, name='verify')
]

products/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True, db_index=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, db_index=True)

    def __str__(self):
        return f'{self.name} | {self.category}'

products/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import os
from django.conf import settings

from django.views.generic import DetailView

from products.models import Product, ProductCategory

from django.core.cache import cache

MODULE_DIR = os.path.dirname(__file__)


# Create your views here.

def get_links_category():
    if settings.LOW_CACHE:
        key = 'links_category'
        links_category = cache.get(key)

        if links_category is None:
            links_category = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_category)
        return links_category
    else:
        return ProductCategory.objects.filter(is_active=True)

def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product{pk}'
        product = cache.get(key)

        if product is None:
            product = get_object_or_404(Product,pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product,pk=pk)


def get_links_product():
    if settings.LOW_CACHE:
        key = 'links_product'
        links_product = cache.get(key)

        if links_product is None:
            links_product = Product.objects.filter(is_active=True).select_related()
            cache.set(key, links_product)
        return links_product
    else:
        return Product.objects.filter(is_active=True).select_related()

def index(request):
    context = {'title': 'GeekShop'}
    return render(request, 'products/index.html', context)


def products(request, id=None, page=1):
    if id != None:
        products_filter = Product.objects.filter(category_id=id).select_related('category')

    else:
        products_filter = Product.objects.all().select_related('category')
    products_filter = get_links_product()
    paginator = Paginator(products_filter, per_page=3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator(paginator.num_pages)
    context = {
        'title': 'GeekShop - Catalog',
        'categories': get_links_category(),
    }
    context['products'] = products_paginator
    return render(request, 'products/products.html', context)


class ProductPage(DetailView):
    model = Product
    template_name = 'products/product_page.html'
    context_object_name = 'product'

    # def get_context_data(self, category_id=None, *args, **kwargs):
    #     context = super().get_context_data()
    #     context['categories'] = ProductCategory.objects.all()
    #     return context

    def get_context_data(self, category_id=None, *args, **kwargs):
        context = super().get_context_data()

        context['product'] = get_product(self.kwargs.get('pk'))
        context['categories'] = ProductCategory.objects.all()
        return context

products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}

        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}
        <!-- Custom styles for this template -->
        <link href="{% static 'css/index.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <div class="navbar-brand">{% now "jS F Y H:i" %}</div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% else %}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'users:profile' %}">{{ user.username }}#}
{#                            <i class="fas fa-user-circle"></i>#}
{#                        </a>#}
{#                    </li>#}
                    <li class="nav-item">
                        <div class="dropdown">
                            <a class="nav-link dropdown-toggle" href="" data-toggle="dropdown">
                                {{ user.username|default:'Пользователь' }}
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'users:profile' %}">
                                        Профиль
                                    </a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" href="{% url 'ordersapp:list' %}">
                                        Заказы
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    {% if user.is_staff or user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admins:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти <i
                                class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<script src="{% static 'js/baskets.js' %}"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script src="{% static 'js/orders_scripts.js' %}"></script>
</body>

</html>

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

<!-- Page Content -->
{% block content %}
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

products/templates/products/product_page.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

<!-- Page Content -->
{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все товары</a>
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <tbody>
                            <tr>
                                <td>
                                    <div class="card-body">
                                        <h4>Название:</h4>
                                        <p class="card-text">
                                            {{ product.name }}
                                        </p>
                                        <h4>Цена:</h4>
                                        <p class="card-text">{{ product.price }} руб.</p>
                                        <h4>Описание:</h4>
                                        <p class="card-text">{{ product.description }}</p>
                                        <h4>Доступно к заказу:</h4>
                                        <p class="card-text">{{ product.quantity }} шт.</p>
                                    </div>

                                    <div class=" text-center">
                                        <a href="{% url 'baskets:baskets_add' product.id %}" type="button"
                                           class="btn btn-outline-success">
                                            Отправить в корзину
                                        </a>
                                    </div>
                                    <div class=" text-center" style="margin-top: 20px">
                                        <a href="{% url 'products:index' %}" type="button"
                                           class="btn btn-outline-danger">
                                            На главную
                                        </a>
                                    </div>
                                </td>
                                <td>
                                    <a href="#">
                                        <img class="card-img-top"
                                             src="{{ product.image.url }}"
                                             alt="">
                                    </a>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

<!-- Footer -->
{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

<!-- Page Content -->
{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    <a href="{% url 'products:index' %}" class="list-group-item">Все товары</a>
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}"
                           class="list-group-item">{{ category.name }}</a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/slide-3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        {% if product.quantity > 0 %}
                            <div class="col-lg-4 col-md-6 mb-4">
                                <div class="card h-100">
                                    <a href="{% url 'products:product_page' product.id %}">
                                        <img class="card-img-top"
                                             src="{{ product.image.url }}"
                                             alt="">
                                    </a>
                                    <div class="card-body">
                                        <h4 class="card-title">
                                            <a href="{% url 'products:product_page' product.id %}">{{ product.name }}</a>
                                        </h4>
                                        <h5>{{ product.price }} руб.</h5>
                                        <p class="card-text">{{ product.description }}</p>
                                        <p class="card-text">{{ product.category.name }}</p>
                                    </div>
                                    <div class="card-footer text-center">
                                            <a href="{% url 'baskets:baskets_add' product.id %}" type="button"
                                               class="btn btn-outline-success">
                                                Отправить в корзину
                                            </a>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}


                    {% for product in products %}
                        {% if product.quantity <= 0 %}
                            <div class="col-lg-4 col-md-6 mb-4">
                                <div class="card h-100">
                                    <a href="{% url 'products:product_page' product.id %}">
                                        <img class="card-img-top"
                                             src="{{ product.image.url }}"
                                             alt="">
                                    </a>
                                    <div class="card-body">
                                        <h4 class="card-title">
                                            <a href="{% url 'products:product_page' product.id %}">{{ product.name }}</a>
                                        </h4>
                                        <h5>{{ product.price }} руб.</h5>
                                        <p class="card-text">{{ product.description }}</p>
                                        <p class="card-text">{{ product.category.name }}</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <div class="btn btn-danger">
                                            Товара нет в наличии
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if products.has_previous %}
                                    {% url 'products:page' products.previous_page_number %}
                                    {% else %} # {% endif %}" tabindex="-1" aria-disabled="true">Previous</a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item"><a class="page-link"
                                                     href="{% url 'products:page' page %}">{{ page }}</a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link" href="{% if products.has_next %}
                                    {% url 'products:page' products.next_page_number %}
                                    {% else %} # {% endif %}">Next</a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

<!-- Footer -->
{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}